// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nostradamus;

namespace Nostradamus.Migrations
{
    [DbContext(typeof(NostradamusContext))]
    [Migration("20200201154726_PresidentialPrediction")]
    partial class PresidentialPrediction
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Nostradamus.Models.GenericEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("Active");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreationDate");

                    b.Property<string>("DateOccurs");

                    b.Property<string>("Description");

                    b.Property<int?>("EventQualityVoteCount");

                    b.Property<string>("NosterId");

                    b.Property<bool?>("Occurred");

                    b.Property<string>("Title");

                    b.Property<bool?>("Valid");

                    b.HasKey("Id");

                    b.HasIndex("NosterId");

                    b.ToTable("GenericEvent");
                });

            modelBuilder.Entity("Nostradamus.Models.GenericPrediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<int?>("CorrectVoteCount");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreationDate");

                    b.Property<bool>("EventOccurred");

                    b.Property<int?>("GenericEventId");

                    b.Property<int?>("IncorrectVoteCount");

                    b.Property<string>("NosterId");

                    b.Property<string>("OutcomeDescription");

                    b.Property<DateTime?>("SnapEndDate");

                    b.Property<bool>("Valid");

                    b.HasKey("Id");

                    b.HasIndex("GenericEventId");

                    b.HasIndex("NosterId");

                    b.ToTable("GenericPrediction");
                });

            modelBuilder.Entity("Nostradamus.Models.Noster", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime?>("CreationDate");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<DateTime?>("RefreshExpiration");

                    b.Property<string>("RefreshToken");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("Noster");
                });

            modelBuilder.Entity("Nostradamus.Models.NosterScore", b =>
                {
                    b.Property<string>("NosterId");

                    b.Property<int?>("GenericPredictionTotal");

                    b.Property<int?>("RunningTotal");

                    b.Property<string>("UserName");

                    b.HasKey("NosterId");

                    b.ToTable("NosterScore");
                });

            modelBuilder.Entity("Nostradamus.Models.PresidentialPrediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AKVote");

                    b.Property<string>("ALVote");

                    b.Property<string>("ARVote");

                    b.Property<string>("AZVote");

                    b.Property<bool>("Active");

                    b.Property<string>("CAVote");

                    b.Property<string>("COVote");

                    b.Property<string>("CTVote");

                    b.Property<string>("Candidate1");

                    b.Property<int>("Candidate1FaithlessElectors");

                    b.Property<string>("Candidate1Party");

                    b.Property<string>("Candidate1VP");

                    b.Property<string>("Candidate2");

                    b.Property<int>("Candidate2FaithlessElectors");

                    b.Property<string>("Candidate2Party");

                    b.Property<string>("Candidate2VP");

                    b.Property<string>("DEVote");

                    b.Property<string>("Description");

                    b.Property<string>("ElectionWinner");

                    b.Property<string>("ElectoralVoteWinner");

                    b.Property<string>("FLVote");

                    b.Property<string>("GAVote");

                    b.Property<string>("HIVote");

                    b.Property<string>("IAVote");

                    b.Property<string>("IDVote");

                    b.Property<string>("ILVote");

                    b.Property<string>("INVote");

                    b.Property<string>("KSVote");

                    b.Property<string>("KYVote");

                    b.Property<string>("LAVote");

                    b.Property<string>("MAVote");

                    b.Property<string>("MDVote");

                    b.Property<string>("MEVote");

                    b.Property<string>("MIVote");

                    b.Property<string>("MNVote");

                    b.Property<string>("MOVote");

                    b.Property<string>("MSVote");

                    b.Property<string>("MTVote");

                    b.Property<string>("NCVote");

                    b.Property<string>("NDVote");

                    b.Property<string>("NEVote");

                    b.Property<string>("NHVote");

                    b.Property<string>("NJVote");

                    b.Property<string>("NMVote");

                    b.Property<string>("NVVote");

                    b.Property<string>("NYVote");

                    b.Property<string>("NosterId");

                    b.Property<string>("OHVote");

                    b.Property<string>("OKVote");

                    b.Property<string>("ORVote");

                    b.Property<string>("PAVote");

                    b.Property<string>("PopularVoteWinner");

                    b.Property<string>("RIVote");

                    b.Property<string>("SCVote");

                    b.Property<string>("SDVote");

                    b.Property<bool>("Scored");

                    b.Property<DateTime?>("SnapEndDate");

                    b.Property<DateTime?>("SnapStartDate");

                    b.Property<string>("TNVote");

                    b.Property<string>("TXVote");

                    b.Property<string>("UTVote");

                    b.Property<string>("VAVote");

                    b.Property<string>("VTVote");

                    b.Property<bool>("Valid");

                    b.Property<string>("WAVote");

                    b.Property<string>("WIVote");

                    b.Property<string>("WVVote");

                    b.Property<string>("WYVote");

                    b.Property<string>("Why");

                    b.HasKey("Id");

                    b.HasIndex("NosterId");

                    b.ToTable("PresidentialPrediction");
                });

            modelBuilder.Entity("Nostradamus.Models.PresidentialPredictionScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double?>("AKVoteScore");

                    b.Property<double?>("ALVoteScore");

                    b.Property<double?>("ARVoteScore");

                    b.Property<double?>("AZVoteScore");

                    b.Property<double?>("CAVoteScore");

                    b.Property<double?>("COVoteScore");

                    b.Property<double?>("CTVoteScore");

                    b.Property<double?>("Candidate1FaithlessElectorsScore");

                    b.Property<double?>("Candidate1PartyScore");

                    b.Property<double?>("Candidate1Score");

                    b.Property<double?>("Candidate1VPScore");

                    b.Property<double?>("Candidate2FaithlessElectorsScore");

                    b.Property<double?>("Candidate2PartyScore");

                    b.Property<double?>("Candidate2Score");

                    b.Property<double?>("Candidate2VPScore");

                    b.Property<double?>("DEVoteScore");

                    b.Property<double?>("ElectionWinnerScore");

                    b.Property<double?>("ElectoralVoteWinnerScore");

                    b.Property<double?>("FLVoteScore");

                    b.Property<double?>("GAVoteScore");

                    b.Property<double?>("HIVoteScore");

                    b.Property<double?>("IAVoteScore");

                    b.Property<double?>("IDVoteScore");

                    b.Property<double?>("ILVoteScore");

                    b.Property<double?>("INVoteScore");

                    b.Property<double?>("KSVoteScore");

                    b.Property<double?>("KYVoteScore");

                    b.Property<double?>("LAVoteScore");

                    b.Property<double?>("MAVoteScore");

                    b.Property<double?>("MDVoteScore");

                    b.Property<double?>("MEVoteScore");

                    b.Property<double?>("MIVoteScore");

                    b.Property<double?>("MNVoteScore");

                    b.Property<double?>("MOVoteScore");

                    b.Property<double?>("MSVoteScore");

                    b.Property<double?>("MTVoteScore");

                    b.Property<double?>("NCVoteScore");

                    b.Property<double?>("NDVoteScore");

                    b.Property<double?>("NEVoteScore");

                    b.Property<double?>("NHVoteScore");

                    b.Property<double?>("NJVoteScore");

                    b.Property<double?>("NMVoteScore");

                    b.Property<double?>("NVVoteScore");

                    b.Property<double?>("NYVoteScore");

                    b.Property<double?>("OHVoteScore");

                    b.Property<double?>("OKVoteScore");

                    b.Property<double?>("ORVoteScore");

                    b.Property<double?>("PAVoteScore");

                    b.Property<double?>("PopularVoteWinnerScore");

                    b.Property<double?>("RIVoteScore");

                    b.Property<double?>("SCVoteScore");

                    b.Property<double?>("SDVoteScore");

                    b.Property<double?>("ScoreTotal");

                    b.Property<double?>("TNVoteScore");

                    b.Property<double?>("TXVoteScore");

                    b.Property<double?>("UTVoteScore");

                    b.Property<double?>("VAVoteScore");

                    b.Property<double?>("VTVoteScore");

                    b.Property<double?>("WAVoteScore");

                    b.Property<double?>("WIVoteScore");

                    b.Property<double?>("WVVoteScore");

                    b.Property<double?>("WYVoteScore");

                    b.HasKey("Id");

                    b.ToTable("PresidentialPredictionScore");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Nostradamus.Models.Noster")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Nostradamus.Models.Noster")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Nostradamus.Models.Noster")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Nostradamus.Models.Noster")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Nostradamus.Models.GenericEvent", b =>
                {
                    b.HasOne("Nostradamus.Models.Noster", "Noster")
                        .WithMany("GenericEvents")
                        .HasForeignKey("NosterId");
                });

            modelBuilder.Entity("Nostradamus.Models.GenericPrediction", b =>
                {
                    b.HasOne("Nostradamus.Models.GenericEvent", "GenericEvent")
                        .WithMany("GenericPredictions")
                        .HasForeignKey("GenericEventId");

                    b.HasOne("Nostradamus.Models.Noster", "Noster")
                        .WithMany("GenericPredictions")
                        .HasForeignKey("NosterId");
                });

            modelBuilder.Entity("Nostradamus.Models.NosterScore", b =>
                {
                    b.HasOne("Nostradamus.Models.Noster", "Noster")
                        .WithOne("NosterScore")
                        .HasForeignKey("Nostradamus.Models.NosterScore", "NosterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Nostradamus.Models.PresidentialPrediction", b =>
                {
                    b.HasOne("Nostradamus.Models.PresidentialPredictionScore", "PresidientialPredictionScore")
                        .WithOne("PresidentialPrediction")
                        .HasForeignKey("Nostradamus.Models.PresidentialPrediction", "Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Nostradamus.Models.Noster", "Noster")
                        .WithMany()
                        .HasForeignKey("NosterId");
                });
#pragma warning restore 612, 618
        }
    }
}
